### ISSUE TITLE
run_imgnet_resnet18_4bit.sh get the acc？

### ISSUE THREAD

**Issue by GuangyanZhang** [iamkanghyunchoi/qimera#1]
HI，Thank you for your contribution,
I run the repo run_imgnet_resnet18_4bit.sh,I get the acc:
![image](https://user-images.githubusercontent.com/33215594/145411723-aa593255-4f96-43e6-9e7a-8c5f9e1cd512.png)
run the eval_imgnet_resnet18_4bit.sh,the result:
![image](https://user-images.githubusercontent.com/33215594/145412031-40ce36a5-4fa9-45fa-8490-15cffae50ff7.png)

but there is big gap for the paper‘s acc 63.84%,How can I reproduce your work？

**Comment by iamkanghyunchoi** [comment]
Hi, I read your issue and ran my code from the repo. 
![Screen Shot 2021-12-11 at 3 39 57 PM](https://user-images.githubusercontent.com/28946887/145667103-4b14774a-5135-40a8-a713-6c52e7cd46fe.png)
![Screen Shot 2021-12-11 at 3 40 08 PM](https://user-images.githubusercontent.com/28946887/145667108-ff1198a8-22ed-4e70-9be3-1daafe98cd95.png)
![Screen Shot 2021-12-11 at 3 40 16 PM](https://user-images.githubusercontent.com/28946887/145667111-41a5ad5a-342b-43f7-974d-ebf0b2c40e67.png)
I tested on several different environments, but I could not reproduce the error you posted. 

Could you elaborate on your test environment? or any modification compared to the original code?

**Comment by GuangyanZhang** [comment]
the environment:
Python 3.6
torch                  1.8.1
others I want to ran code:pip install -r requirements.txt, but I couldn't found it. 

I couldn't find any more details about the test set，so,I modified the reading of the test set.
Can you give me more details

**Comment by iamkanghyunchoi** [comment]
First of all, I forgot to upload a proper requirements.txt file. Sorry for that, and I'll upload it soon. 
About the test set, we used the original ImageNet dataset. I see the total number of test batches is different from mine (mine:3125, yours:313), so if you didn't change the code, the dataset setting might cause wrong validation results.

**Comment by GuangyanZhang** [comment]
yes, the  dataset setting is 50000 images, in order to train more  faster，I only test 5000 images,5000 and 50000 won't make a big difference.

I review my code reading of the test set,I set  RGB to BGR,Maybe there's an error there，now I train again.

Can you tell me what configuration training mobilenetv2，I use a 2080Ti, bug ：out of memory

**Comment by GuangyanZhang** [comment]
I found different implementation results，such as：
the result for 4w4a result 50: your result was 53.02, but original  zaq result was 70.06,Why such a big gap？

**Comment by iamkanghyunchoi** [comment]
Could you try to test the whole 50,000 images and check the result? I assume it may cause a problem. 
From my experience, MobilenetV2 takes approx. 15GB VRAM, which is not fit to 2080Ti GPU. We used RTX3090 for the experiments. 
About the next question, I think you mention the result of ZAQ.
As we mentioned in our paper, we used the official code from the author.

**Comment by GuangyanZhang** [comment]
Ok, thanks for your reply

**Comment by iamkanghyunchoi** [comment]
It seems that this issue has ended.
Therefore, the issue is closed.
