### ISSUE TITLE
Question about the "generator" module (Not related to GAN model)

### ISSUE THREAD

**Issue by he159ok** [iamkanghyunchoi/qimera#2]
Hi, I meet an issue as below
`ModuleNotFoundError: No module named 'generator'`

May I know which `generator` module by pip or conda that I should install?

**Comment by iamkanghyunchoi** [comment]
Hi, 
The code has two generator modules, Generator (for cifar), Generator_imagenet (for imagenet). 
You can refer to line 452 and 463 respectively in the main.py file.
